package com.wigball.mapstruct.issue.model;

/**
 * The source class from which mapstruct should map. Generated by jaxb.
 */
public class SourceClass {

    private Boolean anXmlFlag;
    private Boolean anotherXmlFlag;

    // jaxb generates is...() although it is a Boolean and not a boolean
    public Boolean isAnXmlFlag() {
        return anXmlFlag;
    }

    public void setAnXmlFlag(Boolean anXmlFlag) {
        this.anXmlFlag = anXmlFlag;
    }

    // jaxb generates is...() although it is a Boolean and not a boolean
    public Boolean isAnotherXmlFlag() {
        return anotherXmlFlag;
    }

    public void setAnotherXmlFlag(Boolean anotherXmlFlag) {
        this.anotherXmlFlag = anotherXmlFlag;
    }
}
