package com.wigball.mapstruct.issue.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;

/**
 * The source class from which mapstruct should map. Generated by jaxb.
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "sourceClass_Type", propOrder = {
        "anXmlFlag",
        "anotherXmlFlag"
})
public class SourceClass {

    private Boolean anXmlFlag;
    private Boolean anotherXmlFlag;

    // jaxb generates is...() although it is a Boolean and not a boolean
    public Boolean isAnXmlFlag() {
        return anXmlFlag;
    }

    public void setAnXmlFlag(Boolean anXmlFlag) {
        this.anXmlFlag = anXmlFlag;
    }

    // jaxb generates is...() although it is a Boolean and not a boolean
    public Boolean isAnotherXmlFlag() {
        return anotherXmlFlag;
    }

    public void setAnotherXmlFlag(Boolean anotherXmlFlag) {
        this.anotherXmlFlag = anotherXmlFlag;
    }
}
